version: '2'

services:

  new-crawler-b:
    build:
      context: ./new_crawler_b
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: new_crawler_b
    volumes:
      - ./new_crawler_b:/app
    depends_on:
      - mysql
      - redis

  sidekiq:
    build:
      context: ./new_crawler_b
      dockerfile: Dockerfile
    container_name: new_crawler_b_sidekiq
    command: bundle exec sidekiq
    volumes:
      - ./new_crawler_b:/app
    depends_on:
      - mysql
      - redis

  crawler-b:
    build:
      context: ./crawler_b
      dockerfile: Dockerfile
    container_name: crawler_b
    ports:
      - "80:80"
    depends_on:
      - mysql
    volumes:
      - ./crawler_b:/var/www/html

  mysql:
    image: mysql
    container_name: crawlerb_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./.data/mysql:/var/lib/mysql

  redis:
    image: redis:3.2-alpine
    container_name: redis
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./.data/redis:/var/lib/redis/data

